import { Inter, Nunito } from "next/font/google";

import { Footer, Header } from "@/components/layout";
import "@/style/globals.scss";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={`${inter.className} bg-secondary container mx-auto`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
